apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: order-ms-placement-rule
  namespace: vaccine-order-ms
  labels:
    name: order-ms-placement-rule
    app: order-ms-app
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: OK
  clusterLabels:
    matchLabels:
      environment: Dev
