apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
 name: nginx-app
 namespace: nginx-app
 labels:
  name: nginx-app
  app: nginx-app 
spec:
 componentKinds:
 - group: app.ibm.com/v1alpha1
   kind: Subscription
 selector:
  matchLabels:
   app: nginx-app
