apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms-deployment
  namespace: vaccine-order-ms
  labels:
    app: order-ms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-ms-app
  template:
    metadata:
      labels:
        app: order-ms-app
    spec:
      containers:
      - name: order-ms-app
        image: nginx:1.14.2
        ports:
        - containerPort: 80