apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: policy-vulnerabilitypolicy
  namespace: kube-system
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: DE.CM Security Continuous Monitoring
    policy.mcm.ibm.com/controls: DE.CM-8 Vulnerability scans
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: policies.ibm.com/v1alpha1
        kind: VulnerabilityPolicy # detect image vulnerabilities
        metadata:
          name: policy-vulnerabilitypolicy-example
        spec:
          namespaceSelector:
            include: ["default","kube-*"]
            exclude: ["kube-system"]
          remediationAction: inform # enforce or inform
          severity: medium
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-policy-vulnerabilitypolicy
  namespace: kube-system
placementRef:
  name: placement-policy-vulnerabilitypolicy
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
subjects:
- name: policy-vulnerabilitypolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: placement-policy-vulnerabilitypolicy
  namespace: kube-system
spec:
  clusterLabels:
    matchExpressions:
      - {key: cloud, operator: In, values: ["MyDataCenter1", "MyDataCenter2"]}
